// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using payroll_app.Data;

namespace payroll_app.Migrations
{
    [DbContext(typeof(payroll_app_context))]
    [Migration("20200201113852_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("payroll_app.Models.repository.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int>("ArrangeOrder")
                        .HasColumnName("Arrange Order")
                        .HasMaxLength(11);

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnName("Department Code")
                        .HasMaxLength(30);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnName("Department Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasAlternateKey("DepartmentCode");

                    b.HasAlternateKey("DepartmentName");

                    b.HasAlternateKey("DepartmentCode", "DepartmentName", "Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("payroll_app.Models.repository.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int>("ArrangeOrder")
                        .HasColumnName("Arrange Order")
                        .HasMaxLength(11);

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasColumnName("Grade Code")
                        .HasMaxLength(30);

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnName("Grade Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasAlternateKey("GradeCode");

                    b.HasAlternateKey("GradeName");

                    b.HasAlternateKey("GradeCode", "GradeName", "Id");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("payroll_app.Models.repository.WorkerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int>("ArrangeOrder")
                        .HasColumnName("Arrange Order")
                        .HasMaxLength(11);

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnName("Category Code")
                        .HasMaxLength(30);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnName("Category Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasAlternateKey("CategoryCode");

                    b.HasAlternateKey("CategoryName");

                    b.HasAlternateKey("CategoryCode", "CategoryName", "Id");

                    b.ToTable("Worker Type");
                });
#pragma warning restore 612, 618
        }
    }
}
